### ISSUE TITLE
How to remove regex from :id and :name parameters?

### ISSUE THREAD

**Issue by awulkan** [xujiajun/gorouter#34]
I like the idea of this router, and I'm planning on using it for an upcoming project. However the automatic regex matching for `:id` and `:name` is bothering me. I don't want to use it, and if I do, I'll provide my own regex. How do I prevent any regex matching from happening for those parameters?

I don't think it's a good idea to assume the regex that people want to use for random parameters, it can cause bugs and other problems. But that's just my opinion.

**Comment by xujiajun** [comment]
@awulkan thanks your question.

you mean that you don't want to use automatic regex matching for :id and :name ? right?
you can custom it  like this:

```
	mux := gorouter.New()

	mux.GET("/user/{id:[a-zA-Z0-9]+}", func(w http.ResponseWriter, r *http.Request) {
		//fmt.Println(gorouter.GetParam(r,"id")) //get `id` parameter value from url
		w.Write([]byte("/user/{id:[a-zA-Z0-9]+}"))
	})

	mux.GET("/name/{name:[a-zA-Z0-9]+}", func(w http.ResponseWriter, r *http.Request) {
		//fmt.Println(gorouter.GetParam(r,"name")) //get `name` parameter value from url
		w.Write([]byte("/name/{id:[a-zA-Z0-9]+}"))
	})
```

**Comment by awulkan** [comment]
I mean I don't want any regex checking at all for any parameter by default. I want to opt-in manually to any regex checks used.

**Comment by xujiajun** [comment]
@awulkan I see. Thanks your good advise. Actually the default way is designed to provide convenience (maybe only for someones) and compatible with the grammar (like `:id` ),so if you don't want to use it , i recommend use this grammar，
like this：`{id:[a-zA-Z0-9]+} ` ,it will avoid the questions you mentioned.

> if use default regex checks unless you know what you're doing

**Comment by awulkan** [comment]
Yes, I figured that I can override it. Maybe I will have to fork this repo and remove it myself though. I don't want the to be any default regex at all for my paths since I can sense it will cause problems down the line. And I don't want to override it everywhere in my app, that's very error prone. :/

**Comment by ije** [comment]
i also prefer to remove the default regex  of `:id` and `:name`.
example sometime the `id` param could be a string not number, maybe it is an over-design i think.
anyway i will try to use it in my project, thanks!

**Comment by vision9527** [comment]
I don't understand the meaning of question, but I am interesting this.Don't use regex function or rich document about regex function? Can this method can solve this question? 

haha.
