### ISSUE TITLE
can't match suffix '/' in url

### ISSUE THREAD

**Issue by vision9527** [xujiajun/gorouter#50]
![image](https://user-images.githubusercontent.com/25179277/60397345-bb2d3f00-9b7e-11e9-8204-b3453271f603.png)

![image](https://user-images.githubusercontent.com/25179277/60397354-ce400f00-9b7e-11e9-8e8d-22dd1c374da1.png)

Server side code:
```
func main() {
	mux := gorouter.New()
	//url regex match
	mux.GET("/user/{id:[0-9]+}/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("match user/{id:[0-9]+} !"))
	})

	log.Fatal(http.ListenAndServe(":8181", mux))
}

```

**Comment by vision9527** [comment]
![image](https://user-images.githubusercontent.com/25179277/60397375-2119c680-9b7f-11e9-8aec-e4e406ac4557.png)

**Comment by xujiajun** [comment]
@vision9527  #51
